import { primaryProductImage } from "@/lib/product-images";

/**
 * Gegenereerde productfoto's (960×1200, witte achtergrond).
 * De map wint van imageUrl in de database, zodat een preview de foto's toont
 * zonder een schrijfactie op Neon. Merkfoto's (BARÚ, Rabeko, Appelaere, …)
 * en Marie's eigen foto's staan hier niet in.
 */
export const GENERATED_PRODUCT_PHOTO_BY_SLUG: Readonly<Record<string, string>> = {
  "aardbeientaart": "/images/products/generated/aardbeientaart.webp",
  "biscuit-aardbei": "/images/products/generated/biscuit-aardbei.webp",
  "biscuit-advocaat": "/images/products/generated/biscuit-advocaat.webp",
  "biscuit-fruit": "/images/products/generated/biscuit-fruit.webp",
  "biscuit-ganache": "/images/products/generated/biscuit-ganache.webp",
  "biscuit-marsepeinen-boord": "/images/products/generated/biscuit-marsepeinen-boord.webp",
  "biscuitblokje-1p": "/images/products/generated/biscuitblokje-1p.webp",
  "biscuitblokje-cab-mokka-1p": "/images/products/generated/biscuitblokje-cab-mokka-1p.webp",
  "biscuitblokje-cab-vanille-1p": "/images/products/generated/biscuitblokje-cab-vanille-1p.webp",
  "biscuitgebakje-advocaat-1p": "/images/products/generated/biscuitgebakje-advocaat-1p.webp",
  "biscuitgebakje-marsepein-1p": "/images/products/generated/biscuitgebakje-marsepein-1p.webp",
  "biscuittip": "/images/products/generated/biscuittip.webp",
  "biscuittip-grand-manier": "/images/products/generated/biscuittip-grand-manier.webp",
  "biscuittip-aardbeien": "/images/products/generated/biscuittip-aardbeien.webp",
  "biscuittip-ganache": "/images/products/generated/biscuittip-ganache.webp",
  "cab-javanais": "/images/products/generated/cab-javanais.webp",
  "cab-kardinaaltje": "/images/products/generated/cab-kardinaaltje.webp",
  "cab-miserable": "/images/products/generated/cab-miserable.webp",
  "cab-neufchatel": "/images/products/generated/cab-neufchatel.webp",
  "zwaantje": "/images/products/generated/zwaantje.webp",
  "zwaantje-suikerarm": "/images/products/generated/zwaantje-suikerarm.webp",
  "biscuit-cab-mokka": "/images/products/generated/biscuit-cab-mokka.webp",
  "biscuit-cab-vanille": "/images/products/generated/biscuit-cab-vanille.webp",
  "botercake": "/images/products/generated/botercake.webp",
  "lange-appelcake": "/images/products/generated/lange-appelcake.webp",
  "lange-kriekencake": "/images/products/generated/lange-kriekencake.webp",
  "ronde-appelcake": "/images/products/generated/ronde-appelcake.webp",
  "croissant-chocolade": "/images/products/generated/croissant-chocolade.webp",
  "croissant-aardbei": "/images/products/generated/croissant-aardbei.webp",
  "croissant-amandel": "/images/products/generated/croissant-amandel.webp",
  "berliner-bol-pudding": "/images/products/generated/berliner-bol-pudding.webp",
  "berliner-bol-pudding-chocolade": "/images/products/generated/berliner-bol-pudding-chocolade.webp",
  "chocoladebol-creme": "/images/products/generated/chocoladebol-creme.webp",
  "chocoladebol-slagroom": "/images/products/generated/chocoladebol-slagroom.webp",
  "donut-chocolade": "/images/products/generated/donut-chocolade.webp",
  "donut-gesuikerd": "/images/products/generated/donut-gesuikerd.webp",
  "donut-marshmellow": "/images/products/generated/donut-marshmellow.webp",
  "donut-roze-stippen": "/images/products/generated/donut-roze-stippen.webp",
  "donut-witte-stippen": "/images/products/generated/donut-witte-stippen.webp",
  "donut-yellow-frutti": "/images/products/generated/donut-yellow-frutti.webp",
  "eclair-mokka": "/images/products/generated/eclair-mokka.webp",
  "mini-berliner-bol": "/images/products/generated/mini-berliner-bol.webp",
  "roomhoorntje": "/images/products/generated/roomhoorntje.webp",
  "aardbeitip": "/images/products/generated/aardbeitip.webp",
  "fruittaart": "/images/products/generated/fruittaart.webp",
  "fruittip": "/images/products/generated/fruittip.webp",
  "kriekentip": "/images/products/generated/kriekentip.webp",
  "boerengrof-rond": "/images/products/generated/boerengrof-rond.webp",
  "lang-grof": "/images/products/generated/lang-grof.webp",
  "lang-grof-zoutarm": "/images/products/generated/lang-grof-zoutarm.webp",
  "lang-panter": "/images/products/generated/lang-panter.webp",
  "lang-volkoren": "/images/products/generated/lang-volkoren.webp",
  "rond-grof": "/images/products/generated/rond-grof.webp",
  "volkoren-plus": "/images/products/generated/volkoren-plus.webp",
  "frikandelrol": "/images/products/generated/frikandelrol.webp",
  "worstenbrood": "/images/products/generated/worstenbrood.webp",
  "bavarois-aardbeien-4p": "/images/products/generated/bavarois-aardbeien-4p.webp",
  "bavarois-framboos-5-6p": "/images/products/generated/bavarois-framboos-5-6p.webp",
  "bavarois-passie-5-6p": "/images/products/generated/bavarois-passie-5-6p.webp",
  "foret-noir": "/images/products/generated/foret-noir.webp",
  "framboise-4p": "/images/products/generated/framboise-4p.webp",
  "javanais": "/images/products/generated/javanais.webp",
  "miserable": "/images/products/generated/miserable.webp",
  "piece-monte": "/images/products/generated/piece-monte.webp",
  "sint-honore": "/images/products/generated/sint-honore.webp",
  "smostaartje": "/images/products/generated/smostaartje.webp",
  "sultana-5-6p": "/images/products/generated/sultana-5-6p.webp",
  "tarte-maison": "/images/products/generated/tarte-maison.webp",
  "abrikozenkoek": "/images/products/generated/abrikozenkoek.webp",
  "appelkoek": "/images/products/generated/appelkoek.webp",
  "bloemsuiker-frangipanekoek": "/images/products/generated/bloemsuiker-frangipanekoek.webp",
  "boterkoek": "/images/products/generated/boterkoek.webp",
  "boterkoek-glazuur": "/images/products/generated/boterkoek-glazuur.webp",
  "boterkoek-rozijnen": "/images/products/generated/boterkoek-rozijnen.webp",
  "choco-twister": "/images/products/generated/choco-twister.webp",
  "chocoladekoek-creme": "/images/products/generated/chocoladekoek-creme.webp",
  "chocoladekoek-hagelslag": "/images/products/generated/chocoladekoek-hagelslag.webp",
  "chocoladekoek-zonder-afwerking": "/images/products/generated/chocoladekoek-zonder-afwerking.webp",
  "confituurkoek": "/images/products/generated/confituurkoek.webp",
  "cremekoek-chocolade": "/images/products/generated/cremekoek-chocolade.webp",
  "cremekoek-suiker": "/images/products/generated/cremekoek-suiker.webp",
  "dubbele-chocoladekoek": "/images/products/generated/dubbele-chocoladekoek.webp",
  "kriekenkoek": "/images/products/generated/kriekenkoek.webp",
  "pecannotenkoek": "/images/products/generated/pecannotenkoek.webp",
  "pralinkoek": "/images/products/generated/pralinkoek.webp",
  "slagroomkoek-suiker": "/images/products/generated/slagroomkoek-suiker.webp",
  "spiegel": "/images/products/generated/spiegel.webp",
  "spiegel-aardbeien": "/images/products/generated/spiegel-aardbeien.webp",
  "appelflap": "/images/products/generated/appelflap.webp",
  "bernardin": "/images/products/generated/bernardin.webp",
  "carre-confituur": "/images/products/generated/carre-confituur.webp",
  "frangipanetartelette": "/images/products/generated/frangipanetartelette.webp",
  "glace": "/images/products/generated/glace.webp",
  "kattetong": "/images/products/generated/kattetong.webp",
  "mini-bokkepootjes-kg": "/images/products/generated/mini-bokkepootjes-kg.webp",
  "pruimentartelette": "/images/products/generated/pruimentartelette.webp",
  "reuze-bokkepoot": "/images/products/generated/reuze-bokkepoot.webp",
  "rijsttartelette": "/images/products/generated/rijsttartelette.webp",
  "bananentaart": "/images/products/generated/bananentaart.webp",
  "kriekentaart": "/images/products/generated/kriekentaart.webp",
  "bavarois-aardbei-1p": "/images/products/generated/bavarois-aardbei-1p.webp",
  "bavarois-framboos-1p": "/images/products/generated/bavarois-framboos-1p.webp",
  "bavarois-passie-1p": "/images/products/generated/bavarois-passie-1p.webp",
  "chocomousse": "/images/products/generated/chocomousse.webp",
  "flan-bresiliennetip": "/images/products/generated/flan-bresiliennetip.webp",
  "flantip-natuur": "/images/products/generated/flantip-natuur.webp",
  "merveillieux": "/images/products/generated/merveillieux.webp",
  "profiterol-chocolade-creme-kg": "/images/products/generated/profiterol-chocolade-creme-kg.webp",
  "profiterol-suiker-slagroom-kg": "/images/products/generated/profiterol-suiker-slagroom-kg.webp",
  "rijsttip": "/images/products/generated/rijsttip.webp",
  "riz-condez": "/images/products/generated/riz-condez.webp",
  "sultana-1p": "/images/products/generated/sultana-1p.webp",
  "tarte-maison-tip": "/images/products/generated/tarte-maison-tip.webp",
  "tip-normandische-appeltaart": "/images/products/generated/tip-normandische-appeltaart.webp",
  "tiramisu-1p": "/images/products/generated/tiramisu-1p.webp",
  "piccolo-wit": "/images/products/generated/piccolo-wit.webp",
  "bagnat-grof": "/images/products/generated/bagnat-grof.webp",
  "bagnat-wit": "/images/products/generated/bagnat-wit.webp",
  "hotelbroodje-grof": "/images/products/generated/hotelbroodje-grof.webp",
  "hotelbroodje-wit": "/images/products/generated/hotelbroodje-wit.webp",
  "mastel-met-kaneel": "/images/products/generated/mastel-met-kaneel.webp",
  "mastel-zonder-kaneel": "/images/products/generated/mastel-zonder-kaneel.webp",
  "stokbrood-grof": "/images/products/generated/stokbrood-grof.webp",
  "stokbrood-half-multigranen": "/images/products/generated/stokbrood-half-multigranen.webp",
  "stokbrood-rustiek": "/images/products/generated/stokbrood-rustiek.webp",
  "stokbrood-wit": "/images/products/generated/stokbrood-wit.webp",
  "meringue-torsado-schuimpje": "/images/products/generated/meringue-torsado-schuimpje.webp",
  "fc-de-kampioenenbrood": "/images/products/generated/fc-de-kampioenenbrood.webp",
  "multicroc": "/images/products/generated/multicroc.webp",
  "pompoenbrood": "/images/products/generated/pompoenbrood.webp",
  "sovital": "/images/products/generated/sovital.webp",
  "spekkelbrood": "/images/products/generated/spekkelbrood.webp",
  "speltbrood": "/images/products/generated/speltbrood.webp",
  "synergiebrood": "/images/products/generated/synergiebrood.webp",
  "vita-plus": "/images/products/generated/vita-plus.webp",
  "vita-plus-havermout": "/images/products/generated/vita-plus-havermout.webp",
  "waldkorn": "/images/products/generated/waldkorn.webp",
  "zwartewoudbrood": "/images/products/generated/zwartewoudbrood.webp",
  "flan-bresilienne": "/images/products/generated/flan-bresilienne.webp",
  "flan-natuur": "/images/products/generated/flan-natuur.webp",
  "frangipanetaart": "/images/products/generated/frangipanetaart.webp",
  "mattetaart": "/images/products/generated/mattetaart.webp",
  "soireekes-mini-patekes": "/images/products/generated/soireekes-mini-patekes.webp",
  "tartelette-aardbei": "/images/products/generated/tartelette-aardbei.webp",
  "tartelette-banaan": "/images/products/generated/tartelette-banaan.webp",
  "tartelette-citroen-meringue": "/images/products/generated/tartelette-citroen-meringue.webp",
  "tartelette-fruit": "/images/products/generated/tartelette-fruit.webp",
  "ananas-cocostegel-1p": "/images/products/generated/ananas-cocostegel-1p.webp",
  "broodpuddingspie": "/images/products/generated/broodpuddingspie.webp",
  "semoule": "/images/products/generated/semoule.webp",
  "semoule-met-rozijnen": "/images/products/generated/semoule-met-rozijnen.webp",
  "vlaai": "/images/products/generated/vlaai.webp",
  "wiel-grof": "/images/products/generated/wiel-grof.webp",
  "wiel-grof-zaadjes": "/images/products/generated/wiel-grof-zaadjes.webp",
  "wiel-wit": "/images/products/generated/wiel-wit.webp",
  "wiel-wit-zaadjes": "/images/products/generated/wiel-wit-zaadjes.webp",
  "boerenwit-rond": "/images/products/generated/boerenwit-rond.webp",
  "lang-galet": "/images/products/generated/lang-galet.webp",
  "lang-tijger": "/images/products/generated/lang-tijger.webp",
  "rond-galet": "/images/products/generated/rond-galet.webp",
  "appeltjesbrood": "/images/products/generated/appeltjesbrood.webp",
  "chocoladebolleke": "/images/products/generated/chocoladebolleke.webp",
  "chocoladebrood": "/images/products/generated/chocoladebrood.webp",
  "koekenbrood": "/images/products/generated/koekenbrood.webp",
  "notenbrood": "/images/products/generated/notenbrood.webp",
  "ovenmolleken-rozijnenbrood": "/images/products/generated/ovenmolleken-rozijnenbrood.webp",
  "rozijnenbolleke": "/images/products/generated/rozijnenbolleke.webp",
  "rozijnenbrood": "/images/products/generated/rozijnenbrood.webp",
  "suikerbrood": "/images/products/generated/suikerbrood.webp",
  "waldkorn-noten-rozijnen": "/images/products/generated/waldkorn-noten-rozijnen.webp",
  "waldkorn-vierkant": "/images/products/generated/waldkorn-vierkant.webp",
  "croissant": "/images/products/generated/croissant.webp",
  "eclair": "/images/products/generated/eclair.webp",
  "lang-wit": "/images/products/generated/lang-wit.webp",
  "lange-rozijnenkoek": "/images/products/generated/lange-rozijnenkoek.webp",
  "ronde-rozijnenkoek": "/images/products/generated/ronde-rozijnenkoek.webp",
  "mini-chocoladebroodje": "/images/products/generated/mini-chocoladebroodje.webp",
  "rijsttaart": "/images/products/generated/rijsttaart.webp",
  "pistolet-grof": "/images/products/generated/pistolet-grof.webp",
  "pistolet-grof-maanzaad": "/images/products/generated/pistolet-grof-maanzaad.webp",
  "pistolet-grof-sesamzaad": "/images/products/generated/pistolet-grof-sesamzaad.webp",
  "pistolet-kaiser": "/images/products/generated/pistolet-kaiser.webp",
  "pistolet-tijger": "/images/products/generated/pistolet-tijger.webp",
  "pistolet-vita-plus": "/images/products/generated/pistolet-vita-plus.webp",
  "pistolet-vloer": "/images/products/generated/pistolet-vloer.webp",
  "pistolet-wit": "/images/products/generated/pistolet-wit.webp",
  "pistolet-wit-maanzaad": "/images/products/generated/pistolet-wit-maanzaad.webp",
  "pistolet-wit-sesamzaad": "/images/products/generated/pistolet-wit-sesamzaad.webp",
};

export function generatedProductPhoto(slug: string | null | undefined): string | null {
  if (!slug) return null;
  return GENERATED_PRODUCT_PHOTO_BY_SLUG[slug] ?? null;
}

/** Gegenereerde foto als die er is, anders de foto uit de database. */
export function resolveProductPhoto(
  slug: string | null | undefined,
  imageUrl: string | null | undefined,
): string | null {
  return generatedProductPhoto(slug) ?? primaryProductImage(imageUrl);
}
